### ISSUE TITLE
Добавить проект общих утилит

### ISSUE THREAD

**Issue by vildar82** [ReactiveBIM/RxBim.Tools#18]
Думаю нужно добавить проект с общими утилитами - расширениями и прочее, не связаными с автокадом или ревитом.
Типа **RxBim.Tools.Common**?
Математические расширения, cтроковые расширения.
А то, сейчас они размазываются по всем проектам тут и в плагинах.

**Comment by zagor-dmtr** [comment]
Поддерживаю предложение

**Comment by pavlovek** [comment]
Добавлен проект RxBim.Tools
