### ISSUE TITLE
TableBuilder: Single border type setting.

### ISSUE THREAD

**Issue by zagor-dmtr** [ReactiveBIM/RxBim.Tools#19]
Add to the format builder the ability to set the type for an individual border.
For example, now it is done like this:
`table.ToRows().Skip(2).First().ObjectForBuild.Format.Borders.Top = CellBorderType.Bold;`
And something like this is required:
`table.ToRows().Skip(2).First().SetFormat(f => f.SetTopBorder(CellBorderType.Bold));`

**Comment by vildar82** [comment]
А нельзя дать сам формат для установки свойств самому?
table.ToRows().Skip(2).First().SetFormat(f => f.Borders.Top = CellBorderType.Bold);
