### ISSUE TITLE
Excel. Перенос слов по ширине столбца

### ISSUE THREAD

**Issue by vildar82** [ReactiveBIM/RxBim.Tools#29]
Сейчас всем столбцам задается AdjustToContents - т.е. установка ширины столбцов по содержимому.
Наверно это надо задавать в параметрах конвертера. AdjustToContents или тип переноса текста (Wrap).

https://t.me/c/1337599425/1927
_Только может в екселе сделать перенос по словам? Некоторые длинные названия ломают табличку_
![image](https://user-images.githubusercontent.com/1446481/195276010-935387db-3e8b-4a6a-82e1-a754b86cd6fd.png)

**Comment by pavlovek** [comment]
1. Добавить в CellFormat параметр для необходимости переноса слов (по умолчанию True)
2. Добавить в CellFormat параметр автоопределения высоты строки
3. Поменять в Excel конвертере хардкод задания переноса на определение по CellFormat
