### ISSUE TITLE
TableBuilder Refactoring 2

### ISSUE THREAD

**Issue by vildar82** [ReactiveBIM/RxBim.Tools#48]
1. Можно упростить интерфейсы
` ICellBuilder<Cell>, IColumnBuilder<Cell>, IRowBuilder<Cell>, ITableBuilder<Cell>`
 без указания Cell?
2. Упростить неймспейсы: namespace RxBim.Tools.TableBuilder.Builders; RxBim.Tools.TableBuilder.Styles; RxBim.Tools.TableBuilder.Content; 
3. Исчезли ObjectForBuild и ToTable() у билдеров строки и колонки.
4. CellFormatStyleBuilder SetBorders(b => b.SetBorders()) - не красиво

**Comment by pavlovek** [comment]
по первому пункту не очень понятно что имеешь в виду

**Comment by vildar82** [comment]
форматирование съело немного. поправил.

**Comment by vildar82** [comment]
CellsSetBuilder смущает (

**Comment by pavlovek** [comment]
1. убрать `ObjectForBuild`, заменив на реализацию `IBuilder<T>`
2. в конструкторе билдеров делать копию объектов

**Comment by vildar82** [comment]
1. ObjectForBuild сделал protected. добавил IBuilder<T>.
2. Добавил методы Clone в объекты билдеров.
